version: '3'
services:
  app:
    image: chinmayapradhan/reddit-app:1.0
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
